keycloak:
  realm: Busent
  resource: busent-app
  auth-server-url: http://localhost:8080
  public-client: true
  use-resource-role-mappings: true
  security-constraints[0]:
    authRoles[0]: users
    securityCollections[0]:
      patterns[0]: /users

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Busent
          jwk-set-uri: http://localhost:8080/realms/Busent/protocol/openid-connect/certs
  application:
    name: Busent
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: create-drop
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "010800"
    driverClassName: org.postgresql.Driver

server:
  port: '8081'

  #security:
  #require-ssl: 'true'


